package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import com.mongodb.MongoException;


import javafx.event.ActionEvent;

public class Window2__Controller {
	@FXML
    private TextField txtuserN;
    @FXML 
    private TextField txtFID;
    @FXML
    private TextField txtLoc;

	// Event Listener on Button.onAction
	@FXML
	public void Back(ActionEvent event)  {
		 try {
	  	
	  	((Node)event.getSource()).getScene().getWindow().hide();
	      Stage primaryStage = new Stage();
	      FXMLLoader loader = new FXMLLoader();
	      Pane root = loader.load(getClass().getResource("Menu.fxml").openStream());                
	      Scene  scene = new Scene(root);
	      scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	      primaryStage.setScene(scene);
	      primaryStage.setTitle("Menu");
	      primaryStage.show();
		 }catch (Exception e) {
			 
		 }
	}
	@FXML
	public void changeDet(ActionEvent event) throws Exception {
		((Node)event.getSource()).getScene().getWindow().hide();
        Stage primaryStage = new Stage();
        FXMLLoader loader = new FXMLLoader();
        Pane root = loader.load(getClass().getResource("Window2_1.fxml").openStream());                
        Scene  scene = new Scene(root);
        scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
        primaryStage.setScene(scene);
        primaryStage.setTitle("Change Details");
        primaryStage.show();
       
		// TODO Autogenerated
	}
	@FXML
	public void delete(ActionEvent event) throws Exception {
		 Stage primaryStage = new Stage();
	        Parent root = FXMLLoader.load(getClass().getResource("Window2_2.fxml"));
	        primaryStage.setTitle("Delete");
	        primaryStage.setScene(new Scene(root));
	        primaryStage.show();
		
       
		// TODO Autogenerated
	}
	@FXML
	public void Back2(ActionEvent event)  {
		 try {
	  	
	  	((Node)event.getSource()).getScene().getWindow().hide();
	      Stage primaryStage = new Stage();
	      FXMLLoader loader = new FXMLLoader();
	      Pane root = loader.load(getClass().getResource("Window2__.fxml").openStream());                
	      Scene  scene = new Scene(root);
	      scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	      primaryStage.setScene(scene);
	      primaryStage.setTitle("Change/Delete Office Move");
	      primaryStage.show();
		 }catch (Exception e) {
			 
		 }
	}
	
	@FXML
	public void Update(ActionEvent event) throws Exception {
    	
    	
		try {
			String username = this.txtuserN.getText();
			String id = this.txtFID.getText();
			String location = this.txtLoc.getText();


	    	Mongo mongo = new Mongo("localhost", 27017);
			DB db = mongo.getDB("ndw");
			DBCollection collection = db.getCollection("Office_Moves");
			
			BasicDBObject searchQuery = new BasicDBObject().append("User Name",username);
			collection.remove(searchQuery);
			
			BasicDBObject document = new BasicDBObject();
			document.put("User Name", username);
			document.put("Furniture ID", id);
			document.put("Location", location);
			
			collection.insert(document);
			
		} catch (MongoException e) {
			e.printStackTrace();
		    }

	}
}
